import React from "react";
import {
  Lock,
  Bot,
  Brain,
  Palette,
  Globe,
  Mic,
  Terminal,
  BookOpen,
  Gamepad2,
  AppWindow,
  Zap,
  Video,
  Code,
  Briefcase,
  Smartphone,
  Layout,
  Sparkles,
  Twitter,
  Linkedin,
  Instagram,
  Github,
  Mail,
  Home,
  Link as LinkIcon,
  ShoppingBag,
  LayoutGrid,
  Newspaper,
  Book,
  User,
  Star,
  Share2,
  Users,
} from "lucide-react";
import { ProjectType } from "../types";

type Category =
  | "Home"
  | "Links"
  | "Projects"
  | "Apps"
  | "Automation"
  | "Ebooks"
  | "Content"
  | "About"
  | "Reviews"
  | "Connect"
  | "Success"
  | "Store"
  | "Journal"
  | "Vortex"
  | "Services"
  | "Prompts"
  | "Community";

export const categoryDescriptions: Record<string, string> = {
  All: "Explore my complete portfolio of projects, apps, and experiments.",
  "AI Solutions":
    "Advanced artificial intelligence tools and automated workflows.",
  "Apps & Dev":
    "Full-stack applications, developer tools, and software projects.",
  "Interactive Experiences":
    "Immersive 3D worlds, games, and creative web experiences.",
  "My Personal Apps":
    "Private tools and experimental projects built for personal use.",
};

export const tabs: { name: Category; icon: React.ReactNode }[] = [
  { name: "Home", icon: <Home size={18} /> },
  { name: "Links", icon: <LinkIcon size={18} /> },
  { name: "Store", icon: <ShoppingBag size={18} /> },
  { name: "Apps", icon: <LayoutGrid size={18} /> },
  { name: "Journal", icon: <Newspaper size={18} /> },
  { name: "Projects", icon: <AppWindow size={18} /> },
  { name: "Ebooks", icon: <Book size={18} /> },
  { name: "Content", icon: <Newspaper size={18} /> },
  { name: "Automation", icon: <Bot size={18} /> },
  { name: "About", icon: <User size={18} /> },
  { name: "Reviews", icon: <Star size={18} /> },
  { name: "Connect", icon: <Share2 size={18} /> },
  { name: "Vortex", icon: <Sparkles size={18} /> },
  { name: "Services", icon: <Zap size={18} /> },
  { name: "Prompts", icon: <Terminal size={18} /> },
  { name: "Community", icon: <Users size={18} /> },
];

export const socialTabs = [
  {
    name: "Twitter",
    icon: <Twitter size={18} />,
    url: "https://x.com/Mr_AbdulrahmanT",
  },
  { name: "LinkedIn", icon: <Linkedin size={18} />, url: "#" },
  { name: "Instagram", icon: <Instagram size={18} />, url: "#" },
  { name: "GitHub", icon: <Github size={18} />, url: "#" },
  {
    name: "Mail",
    icon: <Mail size={18} />,
    url: "mailto:digital.b3asts@gmail.com",
  },
];

export const projects: ProjectType[] = [
  {
    name: "Project X (Unreleased)",
    mainCategory: "My Personal Apps",
    tags: ["Experimental", "AI"],
    pricing: "Private",
    desc: "An experimental AI-driven personal assistant with deep system integration.",
    url: "#",
    previewUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    color: "text-indigo-400",
    bg: "bg-indigo-500/10",
    icon: <Lock size={20} />,
    status: "Development",
  },
  {
    name: "Nexus Engine",
    mainCategory: "My Personal Apps",
    tags: ["Game Engine", "3D"],
    pricing: "Private",
    desc: "A custom 3D rendering engine built from scratch for next-gen interactive experiences.",
    url: "#",
    previewUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    color: "text-rose-400",
    bg: "bg-rose-500/10",
    icon: <Lock size={20} />,
    status: "Development",
  },
  {
    name: "NodeRaptor - n8n Architect",
    mainCategory: "AI Solutions",
    categories: ["Pro Business Suite"],
    tags: ["SaaS", "AI Tools"],
    pricing: "Free",
    desc: "An AI-powered architect for n8n workflows, capable of analyzing, debugging, and building automations directly via your n8n instance.",
    url: "https://noderaptor.netlify.app/",
    previewUrl: "https://noderaptor.netlify.app/",
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    icon: <Bot size={20} />,
    status: "Production",
  },
  {
    name: "O.S.K.A.R. (Sentient Interface)",
    mainCategory: "Interactive Experiences",
    tags: ["AI Tools", "Interactive"],
    pricing: "Free",
    desc: "A full-screen, interactive AI digital desk and companion with dynamic digital eyes, real-time voice, vision, and natural interaction capabilities.",
    url: "https://project-oskar.netlify.app/",
    previewUrl: "https://project-oskar.netlify.app/",
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    icon: <Brain size={20} />,
    status: "Production",
  },
  {
    name: "Noodle Draw",
    mainCategory: "Apps & Dev",
    tags: ["Web", "AI Tools", "Collaborative"],
    pricing: "Free",
    desc: "A professional-grade infinite canvas drawing application with real-time collaboration, tablet pressure sensitivity, and AI creative assistance.",
    url: "https://noodle-draw-akwy.onrender.com",
    previewUrl: "https://noodle-draw-akwy.onrender.com",
    color: "text-pink-400",
    bg: "bg-pink-500/10",
    icon: <Palette size={20} />,
    status: "Production",
  },
  {
    name: "ARGUS // INTELLIGENCE",
    mainCategory: "AI Solutions",
    categories: ["Pro Business Suite"],
    tags: ["SaaS", "Cybersecurity"],
    pricing: "Paid",
    desc: "A high-tech cybersecurity dashboard tracking visitor IP, location, and network details with a live map interface.",
    url: "https://argus-osint-soc.vercel.app/",
    previewUrl: "https://argus-osint-soc.vercel.app/",
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    icon: <Globe size={20} />,
    status: "Production",
  },
  {
    name: "Koe Audio Studio",
    mainCategory: "AI Solutions",
    categories: ["Pro Business Suite"],
    tags: ["SaaS", "AI Tools"],
    pricing: "Paid",
    desc: "Next-generation parametric voice synthesis suite. Voice cloning and advanced speech generation.",
    url: "https://koe-audiostudio.netlify.app/",
    previewUrl: "https://koe-audiostudio.netlify.app/",
    color: "text-purple-400",
    bg: "bg-purple-500/10",
    icon: <Mic size={20} />,
    status: "Production",
  },
  {
    name: "FlowType - Minimalist Touch Typing",
    mainCategory: "Interactive Experiences",
    tags: ["Web", "AI Tools"],
    pricing: "Free",
    desc: "An ultra-minimalist, distraction-free touch typing application with mechanical keyboard sounds, real-time analytics, and AI-generated practice content.",
    url: "https://theflowtype.netlify.app/",
    previewUrl: "https://theflowtype.netlify.app/",
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    icon: <Terminal size={20} />,
    status: "Production",
  },
  {
    name: "Babel | Learn Fictional Languages",
    mainCategory: "Apps & Dev",
    tags: ["Web", "Education"],
    pricing: "Free",
    desc: "Master the languages of the multiverse. A high-end, gamified learning app for fictional tongues like Minionese, Klingon, and High Valyrian.",
    url: "https://babel-learn-fiction.netlify.app/",
    previewUrl: "https://babel-learn-fiction.netlify.app/",
    color: "text-indigo-400",
    bg: "bg-indigo-500/10",
    icon: <BookOpen size={20} />,
    status: "Production",
  },
  {
    name: "Virtuoso Web Piano & Beat Studio",
    mainCategory: "Interactive Experiences",
    tags: ["Web", "Interactive"],
    pricing: "Free",
    desc: "A premium, responsive web music workstation featuring a Grand Piano, multiple synthesizers, and a 16-pad Beat Studio for rhythm creation.",
    url: "https://virtuoso-keys.netlify.app/",
    previewUrl: "https://virtuoso-keys.netlify.app/",
    color: "text-amber-400",
    bg: "bg-amber-500/10",
    icon: <Palette size={20} />,
    status: "Production",
  },
  {
    name: "The Architect's Doodle Trap",
    mainCategory: "Interactive Experiences",
    tags: ["Games"],
    pricing: "Free",
    desc: "A creative puzzle game built for the web.",
    url: "https://the-architects-doodle-trap.netlify.app/",
    previewUrl: "https://the-architects-doodle-trap.netlify.app/",
    color: "text-yellow-400",
    bg: "bg-yellow-500/10",
    icon: <Gamepad2 size={20} />,
    status: "Production",
  },
  {
    name: "Trust Nothing",
    mainCategory: "Interactive Experiences",
    tags: ["Games"],
    pricing: "Free",
    desc: "A psychological thriller game that challenges your perception.",
    url: "https://trust-nothing.netlify.app/",
    previewUrl: "https://trust-nothing.netlify.app/",
    color: "text-red-500",
    bg: "bg-red-500/10",
    icon: <Gamepad2 size={20} />,
    status: "Production",
  },
  {
    name: "Gekko Dash",
    mainCategory: "Interactive Experiences",
    tags: ["Games"],
    pricing: "Free",
    desc: "A fast-paced neon runner game with addictive mechanics.",
    url: "https://gekko-dash.netlify.app/",
    previewUrl: "https://gekko-dash.netlify.app/",
    color: "text-lime-400",
    bg: "bg-lime-500/10",
    icon: <Gamepad2 size={20} />,
    status: "Production",
  },
  {
    name: "Vesper AI Notes",
    mainCategory: "AI Solutions",
    categories: ["Pro Business Suite"],
    tags: ["SaaS", "AI Tools"],
    pricing: "Free",
    desc: "AI-powered note-taking and knowledge base.",
    url: "https://vesper-ai-notes.netlify.app/",
    previewUrl: "https://vesper-ai-notes.netlify.app/",
    color: "text-blue-400",
    bg: "bg-blue-500/10",
    icon: <Bot size={20} />,
    status: "Production",
  },
  {
    name: "Vibelex",
    mainCategory: "Apps & Dev",
    tags: ["Web", "SaaS"],
    pricing: "Free",
    desc: "Modern digital experience platform.",
    url: "https://vibelex.netlify.app/",
    previewUrl: "https://vibelex.netlify.app/",
    color: "text-purple-400",
    bg: "bg-purple-500/10",
    icon: <Globe size={20} />,
    status: "Production",
  },
  {
    name: "Zen Maker",
    mainCategory: "Apps & Dev",
    categories: ["Pro Business Suite"],
    tags: ["SaaS"],
    pricing: "Paid",
    desc: "Minimalist creation tool for focused builders.",
    url: "https://zen-maker.netlify.app/",
    previewUrl: "https://zen-maker.netlify.app/",
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    icon: <Layout size={20} />,
    status: "Production",
  },
  {
    name: "LevelUp Hero",
    mainCategory: "Apps & Dev",
    tags: ["Mobile", "Games"],
    pricing: "Free",
    desc: "Gamified OS for your life's journey.",
    url: "https://levelup-heros-journey-os.vercel.app/",
    previewUrl: "https://levelup-heros-journey-os.vercel.app/",
    color: "text-orange-400",
    bg: "bg-orange-500/10",
    icon: <Smartphone size={20} />,
    status: "Production",
  },
  {
    name: "KAIROS - The AI Cockpit [▴ Beta 4.O]_(z2.0)",
    mainCategory: "AI Solutions",
    categories: ["Pro Business Suite"],
    tags: ["SaaS", "AI Tools"],
    pricing: "Paid",
    desc: "A high-end AI Ad Creative Studio for E-commerce, featuring Brand DNA management, smart image stacking, and advanced editing capabilities powered by Gemini.",
    url: "https://kairos-beta4.vercel.app/",
    previewUrl: "https://kairos-beta4.vercel.app/",
    color: "text-rose-400",
    bg: "bg-rose-500/10",
    icon: <AppWindow size={20} />,
    status: "Beta",
  },
  {
    name: "Kairos Beta",
    mainCategory: "AI Solutions",
    tags: ["SaaS", "AI Tools"],
    pricing: "Paid",
    desc: "Time management redefined for the AI era.",
    url: "https://kairos-beta3.vercel.app/",
    previewUrl: "https://kairos-beta3.vercel.app/",
    color: "text-rose-400",
    bg: "bg-rose-500/10",
    icon: <AppWindow size={20} />,
    status: "Beta",
  },
  {
    name: "Cyber Quest",
    mainCategory: "Interactive Experiences",
    tags: ["Games"],
    pricing: "Free",
    desc: "A futuristic RPG built with React & Three.js.",
    url: "#",
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    icon: <Gamepad2 size={20} />,
    status: "Development",
  },
  {
    name: "SpeakEasy AI",
    mainCategory: "AI Solutions",
    tags: ["Open Source", "AI Tools"],
    pricing: "Free",
    desc: "100% Free AI Text-To-Speech Tool.",
    url: "https://github.com/Mr-ABX/SpeakEasy-AI-Text-To-Speech-Tool---100-Free-by-AbdulrahmanT",
    color: "text-indigo-400",
    bg: "bg-indigo-500/10",
    icon: <Mic size={20} />,
    status: "Production",
  },
  {
    name: "AI Personality Quiz",
    mainCategory: "AI Solutions",
    tags: ["Open Source", "AI Tools"],
    pricing: "Free",
    desc: "Local run AI Personality Quiz Model.",
    url: "https://github.com/Mr-ABX/AI-Personality-Quiz-Model",
    color: "text-pink-400",
    bg: "bg-pink-500/10",
    icon: <Brain size={20} />,
    status: "Production",
  },
  {
    name: "ASCII TypeArt",
    mainCategory: "Apps & Dev",
    tags: ["Open Source", "AI Tools"],
    pricing: "Free",
    desc: "AI art generator for ASCII Canvas.",
    url: "https://github.com/Mr-ABX/ASCII-TypeArt-Canvas-Img-to-Art-",
    color: "text-teal-400",
    bg: "bg-teal-500/10",
    icon: <Palette size={20} />,
    status: "Production",
  },
  {
    name: "GenAI Studio",
    mainCategory: "AI Solutions",
    categories: ["Pro Business Suite"],
    tags: ["SaaS", "AI Tools"],
    pricing: "Paid",
    desc: "Enterprise-grade generative AI platform for content creation.",
    url: "#",
    color: "text-orange-400",
    bg: "bg-orange-500/10",
    icon: <Sparkles size={20} />,
    status: "Beta",
  },
  {
    name: "Fusion Nexus",
    mainCategory: "Web Development Projects",
    tags: ["Web", "Portfolio"],
    pricing: "Free",
    desc: "Advanced web platform and digital solutions.",
    url: "https://fusionnexus.infni-t.com",
    previewUrl: "https://fusionnexus.infni-t.com",
    color: "text-indigo-400",
    bg: "bg-indigo-500/10",
    icon: <Globe size={20} />,
    status: "Production",
  },
  {
    name: "Solution Lab",
    mainCategory: "Web Development Projects",
    tags: ["Web", "Portfolio"],
    pricing: "Free",
    desc: "Innovative solutions and digital lab.",
    url: "https://solutionlab.infni-t.com",
    previewUrl: "https://solutionlab.infni-t.com",
    color: "text-blue-400",
    bg: "bg-blue-500/10",
    icon: <AppWindow size={20} />,
    status: "Production",
  },
  {
    name: "InstaShred",
    mainCategory: "Web Development Projects",
    tags: ["Web", "Portfolio"],
    pricing: "Free",
    desc: "Fitness and shredding platform.",
    url: "https://instashred.com/",
    previewUrl: "https://instashred.com/",
    color: "text-red-400",
    bg: "bg-red-500/10",
    icon: <Zap size={20} />,
    status: "Production",
  },
  {
    name: "Junno Express",
    mainCategory: "Web Development Projects",
    tags: ["Web", "Portfolio"],
    pricing: "Free",
    desc: "E-commerce and express delivery platform.",
    url: "https://junnoexpress.com/",
    previewUrl: "https://junnoexpress.com/",
    color: "text-yellow-400",
    bg: "bg-yellow-500/10",
    icon: <Globe size={20} />,
    status: "Production",
  },
  {
    name: "Recallers",
    mainCategory: "Web Development Projects",
    tags: ["Web", "Portfolio"],
    pricing: "Free",
    desc: "Dog training and recallers platform.",
    url: "https://dogsthat.com/recallers/",
    previewUrl: "https://dogsthat.com/recallers/",
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    icon: <Globe size={20} />,
    status: "Production",
  },
  {
    name: "Video & Motion Graphics Portfolio",
    mainCategory: "Video & Motion Graphics",
    tags: ["Portfolio", "Video"],
    pricing: "Free",
    desc: "A showcase of my video editing, motion graphics, and VFX work.",
    url: "https://www.youtube.com/watch?v=0Wh7MhqeHHA&list=PL7BsW-EOVU09CgVg1O4vk3U6fujfm1xw9",
    color: "text-pink-400",
    bg: "bg-pink-500/10",
    icon: <Video size={20} />,
    status: "Production",
  },
];

export const reviews = [
  {
    name: "Sarah Jenkins",
    role: "CEO, TechFlow",
    location: "UK",
    text: "Abdulrahman completely transformed our lead generation. The n8n automation he built saves us 20 hours a week.",
    rating: 5,
  },
  {
    name: "Rajiv Patel",
    role: "Founder, SaaSify",
    location: "India",
    text: "Incredible AI integration skills. He built our MVP in record time and the code quality is top-notch.",
    rating: 5,
  },
  {
    name: "Michael Chen",
    role: "Director, GrowthOps",
    location: "USA",
    text: "The custom CRM solution is flawless. Highly recommend his business development and technical expertise.",
    rating: 5,
  },
  {
    name: "Aisha Khan",
    role: "Marketing Head",
    location: "Pakistan",
    text: "Not just a developer, but a true strategist. The video editing and design work for our campaign was stunning.",
    rating: 5,
  },
  {
    name: "David Wright",
    role: "Product Manager",
    location: "UK",
    text: "Vesper AI Notes is a game-changer. His ability to build intuitive, fast, and beautiful SaaS products is rare.",
    rating: 5,
  },
  {
    name: "Priya Sharma",
    role: "E-commerce Owner",
    location: "India",
    text: "Automated our entire customer support with Voice AI. We've seen a 40% increase in customer satisfaction.",
    rating: 5,
  },
  {
    name: "James Wilson",
    role: "Startup Founder",
    location: "USA",
    text: "Abdulrahman's UI/UX design skills brought our vision to life. The platform looks modern and luxurious.",
    rating: 5,
  },
  {
    name: "Zainab Ahmed",
    role: "Content Creator",
    location: "Pakistan",
    text: "The auto-posting pipeline he built for my channels is brilliant. I can finally focus on creating content.",
    rating: 5,
  },
  {
    name: "Elena Rodriguez",
    role: "Operations Lead",
    location: "USA",
    text: "We hired him for a complex n8n workflow and he delivered beyond expectations. A true professional.",
    rating: 5,
  },
  {
    name: "Omar Farooq",
    role: "Tech Entrepreneur",
    location: "UK",
    text: "His open-source tools are fantastic. SpeakEasy AI is incredibly useful and well-built.",
    rating: 5,
  },
  {
    name: "Anita Desai",
    role: "Agency Director",
    location: "India",
    text: "Partnering with INFNI-T' was the best decision for our agency. His strategic insights are invaluable.",
    rating: 5,
  },
  {
    name: "Marcus Johnson",
    role: "Indie Hacker",
    location: "USA",
    text: "Zen Maker is exactly what I needed. Minimalist, fast, and perfectly executed.",
    rating: 5,
  },
];

export const companies = [
  { name: "Plotnao", role: "Partner" },
  { name: "Adriel Partners", role: "Collaborator" },
  { name: "Content with Teeth", role: "AI Strategist" },
  { name: "Outlab", role: "Expert" },
  { name: "MSN Global IT Sol", role: "Consultant" },
];

export const skills = [
  { name: "AI Automation", icon: <Bot size={16} />, level: "Expert" },
  { name: "SaaS Development", icon: <Code size={16} />, level: "Expert" },
  { name: "Video Editing", icon: <Video size={16} />, level: "Advanced" },
  { name: "UI/UX Design", icon: <Palette size={16} />, level: "Advanced" },
  { name: "Digital Marketing", icon: <Zap size={16} />, level: "Advanced" },
  { name: "Business Strategy", icon: <Briefcase size={16} />, level: "Expert" },
];
