import React from "react";
import {
  Lock,
  Bot,
  Brain,
  Palette,
  Globe,
  Mic,
  Terminal,
  BookOpen,
  Gamepad2,
  AppWindow,
  Zap,
  Video,
  Code,
  Briefcase,
  Smartphone,
  Layout,
  Sparkles,
  Twitter,
  Linkedin,
  Instagram,
  Github,
  Mail,
  Home,
  Link as LinkIcon,
  ShoppingBag,
  LayoutGrid,
  Newspaper,
  Book,
  User,
  Star,
  Share2,
  Users,
  GraduationCap,
  Music,
  Radio,
  Wrench,
  Rocket,
  FolderGit2,
  Command,
  SlidersHorizontal,
  Cpu,
  Headphones,
  FileText,
  Rss,
  Wand2,
  Send,
  Compass,
} from "lucide-react";
import { ProjectType, ReviewType } from "../types";

type Category =
  | "Home"
  | "Links"
  | "Projects"
  | "CaseStudies"
  | "Apps"
  | "Automation"
  | "Ebooks"
  | "Content"
  | "About"
  | "Reviews"
  | "Connect"
  | "Success"
  | "Store"
  | "Journal"
  | "Vortex"
  | "Services"
  | "Prompts"
  | "Community"
  | "Academy"
  | "Music"
  | "Blog"
  | "Feed"
  | "Toolspedia"
  | "Flagships";

export const categoryDescriptions: Record<string, string> = {
  All: "Explore my complete portfolio of projects, apps, and experiments.",
  "AI Solutions":
    "Advanced artificial intelligence tools and automated workflows.",
  "Apps & Dev":
    "Full-stack applications, developer tools, and software projects.",
  "Interactive Experiences":
    "Immersive 3D worlds, games, and creative web experiences.",
  "My Personal Apps":
    "Private tools and experimental projects built for personal use.",
};

export const tabs: { name: Category; icon: React.ReactNode }[] = [
  { name: "Home", icon: <Compass size={16} strokeWidth={1.35} /> },
  { name: "Links", icon: <LinkIcon size={16} strokeWidth={1.35} /> },
  { name: "Store", icon: <ShoppingBag size={16} strokeWidth={1.35} /> },
  { name: "Apps", icon: <LayoutGrid size={16} strokeWidth={1.35} /> },
  { name: "CaseStudies", icon: <Sparkles size={16} strokeWidth={1.35} /> },
  { name: "Flagships", icon: <Rocket size={16} strokeWidth={1.35} /> },
  { name: "Journal", icon: <BookOpen size={16} strokeWidth={1.35} /> },
  { name: "Projects", icon: <FolderGit2 size={16} strokeWidth={1.35} /> },
  { name: "Ebooks", icon: <Book size={16} strokeWidth={1.35} /> },
  { name: "Automation", icon: <Cpu size={16} strokeWidth={1.35} /> },
  { name: "About", icon: <User size={16} strokeWidth={1.35} /> },
  { name: "Reviews", icon: <Star size={16} strokeWidth={1.35} /> },
  { name: "Connect", icon: <Send size={16} strokeWidth={1.35} /> },
  { name: "Vortex", icon: <Wand2 size={16} strokeWidth={1.35} /> },
  { name: "Services", icon: <SlidersHorizontal size={16} strokeWidth={1.35} /> },
  { name: "Prompts", icon: <Command size={16} strokeWidth={1.35} /> },
  { name: "Community", icon: <Users size={16} strokeWidth={1.35} /> },
  { name: "Academy", icon: <GraduationCap size={16} strokeWidth={1.35} /> },
  { name: "Music", icon: <Headphones size={16} strokeWidth={1.35} /> },
  { name: "Blog", icon: <FileText size={16} strokeWidth={1.35} /> },
  { name: "Feed", icon: <Rss size={16} strokeWidth={1.35} /> },
  { name: "Toolspedia", icon: <Wrench size={16} strokeWidth={1.35} /> },
];

export const socialTabs = [
  {
    name: "Twitter",
    icon: <Twitter size={16} strokeWidth={1.35} />,
    url: "https://x.com/Mr_AbdulrahmanT",
  },
  { name: "LinkedIn", icon: <Linkedin size={16} strokeWidth={1.35} />, url: "#" },
  { name: "Instagram", icon: <Instagram size={16} strokeWidth={1.35} />, url: "#" },
  { name: "GitHub", icon: <Github size={16} strokeWidth={1.35} />, url: "#" },
  {
    name: "Mail",
    icon: <Mail size={16} strokeWidth={1.35} />,
    url: "mailto:digital.b3asts@gmail.com",
  },
];

export const projects: ProjectType[] = [
  {
    name: "MSN Global Trainings Portal & Hub",
    mainCategory: "Web Development Projects",
    categories: ["Web Development Projects", "Pro Business Suite", "AI Solutions"],
    tags: ["Enterprise Portal", "MSN Training Hub", "E-Learning", "MSN Global", "Brand Identity", "Design System", "Case Study", "Flagship"],
    pricing: "Enterprise",
    desc: "A premier digital learning academy & enterprise training hub for MSN Global IT Solutions, featuring modern course navigation, Apple HIG design system, and frictionless enrollment funnels.",
    url: "http://trainings.msn-global.com/",
    previewUrl: "http://trainings.msn-global.com/",
    color: "text-rose-400",
    bg: "bg-rose-500/10",
    icon: <GraduationCap size={20} />,
    status: "Production",
    hasCaseStudy: true,
    caseStudyId: "msn-trainings",
  },
  {
    name: "INFNI-T — AI Digital Ecosystem & Multidisciplinary Agency",
    mainCategory: "Web Development Projects",
    categories: ["Web Development Projects", "Pro Business Suite", "AI Solutions"],
    tags: ["INFNI-T", "AI Digital Ecosystem", "Multidisciplinary Agency", "Enterprise Web", "React", "Design System"],
    pricing: "Free",
    desc: "A flagship high-performance AI digital ecosystem and multidisciplinary agency portal showcasing next-generation AI architectures, responsive spatial layouts, and modern digital design systems.",
    url: "https://infni-t.online",
    previewUrl: "https://infni-t.online",
    color: "text-purple-400",
    bg: "bg-purple-500/10",
    icon: <Globe size={20} />,
    status: "Production",
  },
  {
    name: "Vibelex Platform",
    mainCategory: "Apps & Dev",
    categories: ["Apps & Dev", "Pro Business Suite"],
    tags: ["Web App", "SaaS", "Next-Gen UI", "Platform"],
    pricing: "Free",
    desc: "A modern digital experience platform designed for smooth workflow execution, modular app architecture, and high-performance design.",
    url: "https://vibelex.netlify.app/",
    previewUrl: "https://vibelex.netlify.app/",
    color: "text-purple-400",
    bg: "bg-purple-500/10",
    icon: <Globe size={20} />,
    status: "Production",
  },
  {
    name: "MSN Marketing Video",
    mainCategory: "Video & Motion Graphics",
    categories: ["Video & Motion Graphics", "Graphics & Marketing"],
    tags: ["MSN", "Marketing Video", "Motion Graphics", "Commercial Ads"],
    pricing: "Free",
    desc: "High-impact commercial marketing video crafted for MSN, featuring kinetic typography, 3D motion transitions, and high-framerate visual effects.",
    url: "https://www.youtube.com/watch?v=sU9o-gyVQ8U",
    youtubeId: "sU9o-gyVQ8U",
    previewUrl: "https://www.youtube.com/embed/sU9o-gyVQ8U?enablejsapi=1&autoplay=1&mute=1&loop=1&playlist=sU9o-gyVQ8U&vq=hd720&controls=1&modestbranding=1&rel=0&playsinline=1",
    color: "text-pink-400",
    bg: "bg-pink-500/10",
    icon: <Video size={20} />,
    status: "Production",
  },
  {
    name: "Epic Reaps YT Channel Intro",
    mainCategory: "Video & Motion Graphics",
    categories: ["Video & Motion Graphics", "Graphics & Marketing"],
    tags: ["Epic Reaps", "YouTube Intro", "3D VFX", "Channel Branding"],
    pricing: "Free",
    desc: "Dynamic YouTube channel intro animation created for Epic Reaps, featuring high-energy 3D CGI transitions and sound synchronization.",
    url: "https://www.youtube.com/watch?v=VULB6DCUniI",
    youtubeId: "VULB6DCUniI",
    previewUrl: "https://www.youtube.com/embed/VULB6DCUniI?enablejsapi=1&autoplay=1&mute=1&loop=1&playlist=VULB6DCUniI&vq=hd720&controls=1&modestbranding=1&rel=0&playsinline=1",
    color: "text-indigo-400",
    bg: "bg-indigo-500/10",
    icon: <Video size={20} />,
    status: "Production",
  },
  {
    name: "Trust Nothing",
    mainCategory: "Interactive Experiences",
    categories: ["Interactive Experiences", "Apps & Dev"],
    tags: ["Games", "Psychological Thriller", "Interactive"],
    pricing: "Free",
    desc: "A psychological thriller interactive game that challenges perception and player decision-making in a immersive dark setting.",
    url: "https://trust-nothing.netlify.app/",
    previewUrl: "https://trust-nothing.netlify.app/",
    color: "text-red-500",
    bg: "bg-red-500/10",
    icon: <Gamepad2 size={20} />,
    status: "Production",
  },
  {
    name: "SnapCaption",
    mainCategory: "AI Solutions",
    categories: ["AI Solutions", "Pro Business Suite"],
    tags: ["SaaS", "AI Tools"],
    pricing: "Free",
    desc: "AI-powered caption generation tool for modern creators.",
    url: "https://snapcaption.netlify.app/",
    previewUrl: "https://snapcaption.netlify.app/",
    color: "text-blue-400",
    bg: "bg-blue-500/10",
    icon: <Bot size={20} />,
    status: "Production",
  },
  {
    name: "Junno Express — Logistics & Modern E-Commerce",
    mainCategory: "Web Development Projects",
    categories: ["Web Development Projects", "Pro Business Suite"],
    tags: ["E-Commerce", "Web Design", "Logistics", "Modern UI"],
    pricing: "Free",
    desc: "A sleek, rapid-delivery logistics and modern e-commerce storefront with intuitive catalog browsing, fast page load speeds, and real-time tracking interface.",
    url: "https://junnoexpress.com/",
    previewUrl: "https://junnoexpress.com/",
    color: "text-amber-400",
    bg: "bg-amber-500/10",
    icon: <ShoppingBag size={20} />,
    status: "Production",
  },
  {
    name: "Cinematic Motion & Commercial Ads Reel",
    mainCategory: "Video & Motion Graphics",
    categories: ["Video & Motion Graphics", "Graphics & Marketing"],
    tags: ["Motion Graphics", "Commercials", "3D VFX", "Video Ads"],
    pricing: "Free",
    desc: "A curated commercial portfolio featuring high-impact video ads, 3D kinetic typography, CGI transitions, and brand campaign reels crafted for maximum engagement.",
    url: "https://www.youtube.com/watch?v=0Wh7MhqeHHA&list=PL7BsW-EOVU09CgVg1O4vk3U6fujfm1xw9",
    previewUrl: "https://www.youtube.com/embed/0Wh7MhqeHHA?autoplay=1&mute=1&loop=1&playlist=0Wh7MhqeHHA&controls=0&modestbranding=1&rel=0&playsinline=1",
    color: "text-pink-400",
    bg: "bg-pink-500/10",
    icon: <Video size={20} />,
    status: "Production",
  },
  {
    name: "AB Folio Portal V2",
    mainCategory: "Interactive Experiences",
    categories: ["Web Development Projects", "Pro Business Suite", "Apps & Dev"],
    tags: ["Portfolio V2", "3D Web", "Interactive", "Next-Gen UI", "Showcase"],
    pricing: "Free",
    desc: "The next-generation interactive web experience portal featuring immersive 3D spatial aesthetics, real-time visual dynamics, and high-performance showcase architecture.",
    url: "https://ab-folio-portal-v2.vercel.app/",
    previewUrl: "https://ab-folio-portal-v2.vercel.app/",
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    icon: <Sparkles size={20} />,
    status: "Production",
  },
  {
    name: "NodeRaptor - n8n Architect",
    mainCategory: "AI Solutions",
    categories: ["Pro Business Suite"],
    tags: ["SaaS", "AI Tools"],
    pricing: "Free",
    desc: "An AI-powered architect for n8n workflows, capable of analyzing, debugging, and building automations directly via your n8n instance.",
    url: "https://noderaptor.netlify.app/",
    previewUrl: "https://noderaptor.netlify.app/",
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    icon: <Bot size={20} />,
    status: "Production",
  },
  {
    name: "O.S.K.A.R. (Sentient Interface)",
    mainCategory: "Interactive Experiences",
    tags: ["AI Tools", "Interactive"],
    pricing: "Free",
    desc: "A full-screen, interactive AI digital desk and companion with dynamic digital eyes, real-time voice, vision, and natural interaction capabilities.",
    url: "https://project-oskar.netlify.app/",
    previewUrl: "https://project-oskar.netlify.app/",
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    icon: <Brain size={20} />,
    status: "Production",
  },
  {
    name: "ARGUS // INTELLIGENCE",
    mainCategory: "AI Solutions",
    categories: ["Pro Business Suite"],
    tags: ["SaaS", "Cybersecurity"],
    pricing: "Paid",
    desc: "A high-tech cybersecurity dashboard tracking visitor IP, location, and network details with a live map interface.",
    url: "https://argus-osint-soc.vercel.app/",
    previewUrl: "https://argus-osint-soc.vercel.app/",
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    icon: <Globe size={20} />,
    status: "Production",
  },
  {
    name: "FlowType - Minimalist Touch Typing",
    mainCategory: "Interactive Experiences",
    tags: ["Web", "AI Tools"],
    pricing: "Free",
    desc: "An ultra-minimalist, distraction-free touch typing application with mechanical keyboard sounds, real-time analytics, and AI-generated practice content.",
    url: "https://theflowtype.netlify.app/",
    previewUrl: "https://theflowtype.netlify.app/",
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    icon: <Terminal size={20} />,
    status: "Production",
  },
  {
    name: "Noodle Draw",
    mainCategory: "Apps & Dev",
    categories: ["Web Development Projects", "Apps & Dev"],
    tags: ["Web App", "AI Tools", "Collaborative"],
    pricing: "Free",
    desc: "A professional-grade infinite canvas drawing application with real-time collaboration, tablet pressure sensitivity, and AI creative assistance.",
    url: "https://noodle-draw-akwy.onrender.com",
    previewUrl: "https://noodle-draw-akwy.onrender.com",
    color: "text-pink-400",
    bg: "bg-pink-500/10",
    icon: <Palette size={20} />,
    status: "Production",
  },
  {
    name: "Koe Audio Studio",
    mainCategory: "AI Solutions",
    categories: ["Pro Business Suite"],
    tags: ["SaaS", "AI Tools"],
    pricing: "Paid",
    desc: "Next-generation parametric voice synthesis suite. Voice cloning and advanced speech generation.",
    url: "https://koe-audiostudio.netlify.app/",
    previewUrl: "https://koe-audiostudio.netlify.app/",
    color: "text-purple-400",
    bg: "bg-purple-500/10",
    icon: <Mic size={20} />,
    status: "Production",
  },
  {
    name: "Babel | Learn Fictional Languages",
    mainCategory: "Apps & Dev",
    tags: ["Web", "Education"],
    pricing: "Free",
    desc: "Master the languages of the multiverse. A high-end, gamified learning app for fictional tongues like Minionese, Klingon, and High Valyrian.",
    url: "https://babel-learn-fiction.netlify.app/",
    previewUrl: "https://babel-learn-fiction.netlify.app/",
    color: "text-indigo-400",
    bg: "bg-indigo-500/10",
    icon: <BookOpen size={20} />,
    status: "Production",
  },
  {
    name: "Virtuoso Web Piano & Beat Studio",
    mainCategory: "Interactive Experiences",
    tags: ["Web", "Interactive"],
    pricing: "Free",
    desc: "A premium, responsive web music workstation featuring a Grand Piano, multiple synthesizers, and a 16-pad Beat Studio for rhythm creation.",
    url: "https://virtuoso-keys.netlify.app/",
    previewUrl: "https://virtuoso-keys.netlify.app/",
    color: "text-amber-400",
    bg: "bg-amber-500/10",
    icon: <Palette size={20} />,
    status: "Production",
  },
  {
    name: "The Architect's Doodle Trap",
    mainCategory: "Interactive Experiences",
    tags: ["Games"],
    pricing: "Free",
    desc: "A creative puzzle game built for the web.",
    url: "https://the-architects-doodle-trap.netlify.app/",
    previewUrl: "https://the-architects-doodle-trap.netlify.app/",
    color: "text-yellow-400",
    bg: "bg-yellow-500/10",
    icon: <Gamepad2 size={20} />,
    status: "Production",
  },
  {
    name: "Gekko Dash",
    mainCategory: "Interactive Experiences",
    tags: ["Games"],
    pricing: "Free",
    desc: "A fast-paced neon runner game with addictive mechanics.",
    url: "https://gekko-dash.netlify.app/",
    previewUrl: "https://gekko-dash.netlify.app/",
    color: "text-lime-400",
    bg: "bg-lime-500/10",
    icon: <Gamepad2 size={20} />,
    status: "Production",
  },
  {
    name: "Vesper AI Notes",
    mainCategory: "AI Solutions",
    categories: ["Pro Business Suite"],
    tags: ["SaaS", "AI Tools"],
    pricing: "Free",
    desc: "AI-powered note-taking and knowledge base.",
    url: "https://vesper-ai-notes.netlify.app/",
    previewUrl: "https://vesper-ai-notes.netlify.app/",
    color: "text-blue-400",
    bg: "bg-blue-500/10",
    icon: <Bot size={20} />,
    status: "Production",
  },
  {
    name: "Zen Maker",
    mainCategory: "Apps & Dev",
    categories: ["Pro Business Suite"],
    tags: ["SaaS"],
    pricing: "Paid",
    desc: "Minimalist creation tool for focused builders.",
    url: "https://zen-maker.netlify.app/",
    previewUrl: "https://zen-maker.netlify.app/",
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    icon: <Layout size={20} />,
    status: "Production",
  },
  {
    name: "LevelUp Hero",
    mainCategory: "Apps & Dev",
    tags: ["Mobile", "Games"],
    pricing: "Free",
    desc: "Gamified OS for your life's journey.",
    url: "https://levelup-heros-journey-os.vercel.app/",
    previewUrl: "https://levelup-heros-journey-os.vercel.app/",
    color: "text-orange-400",
    bg: "bg-orange-500/10",
    icon: <Smartphone size={20} />,
    status: "Production",
  },
  {
    name: "KAIROS - The AI Cockpit [▴ Beta 4.O]_(z2.0)",
    mainCategory: "AI Solutions",
    categories: ["Pro Business Suite"],
    tags: ["SaaS", "AI Tools"],
    pricing: "Paid",
    desc: "A high-end AI Ad Creative Studio for E-commerce, featuring Brand DNA management, smart image stacking, and advanced editing capabilities powered by Gemini.",
    url: "https://kairos-beta4.vercel.app/",
    previewUrl: "https://kairos-beta4.vercel.app/",
    color: "text-rose-400",
    bg: "bg-rose-500/10",
    icon: <AppWindow size={20} />,
    status: "Beta",
  },
  {
    name: "Kairos Beta",
    mainCategory: "AI Solutions",
    tags: ["SaaS", "AI Tools"],
    pricing: "Paid",
    desc: "Time management redefined for the AI era.",
    url: "https://kairos-beta3.vercel.app/",
    previewUrl: "https://kairos-beta3.vercel.app/",
    color: "text-rose-400",
    bg: "bg-rose-500/10",
    icon: <AppWindow size={20} />,
    status: "Beta",
  },
  {
    name: "Cyber Quest",
    mainCategory: "Interactive Experiences",
    tags: ["Games"],
    pricing: "Free",
    desc: "A futuristic RPG built with React & Three.js.",
    url: "#",
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    icon: <Gamepad2 size={20} />,
    status: "Development",
  },
  {
    name: "SpeakEasy AI",
    mainCategory: "AI Solutions",
    tags: ["Open Source", "AI Tools"],
    pricing: "Free",
    desc: "100% Free AI Text-To-Speech Tool.",
    url: "https://github.com/Mr-ABX/SpeakEasy-AI-Text-To-Speech-Tool---100-Free-by-AbdulrahmanT",
    color: "text-indigo-400",
    bg: "bg-indigo-500/10",
    icon: <Mic size={20} />,
    status: "Production",
  },
  {
    name: "AI Personality Quiz",
    mainCategory: "AI Solutions",
    tags: ["Open Source", "AI Tools"],
    pricing: "Free",
    desc: "Local run AI Personality Quiz Model.",
    url: "https://github.com/Mr-ABX/AI-Personality-Quiz-Model",
    color: "text-pink-400",
    bg: "bg-pink-500/10",
    icon: <Brain size={20} />,
    status: "Production",
  },
  {
    name: "ASCII TypeArt",
    mainCategory: "Apps & Dev",
    tags: ["Open Source", "AI Tools"],
    pricing: "Free",
    desc: "AI art generator for ASCII Canvas.",
    url: "https://github.com/Mr-ABX/ASCII-TypeArt-Canvas-Img-to-Art-",
    color: "text-teal-400",
    bg: "bg-teal-500/10",
    icon: <Palette size={20} />,
    status: "Production",
  },
  {
    name: "GenAI Studio",
    mainCategory: "AI Solutions",
    categories: ["Pro Business Suite"],
    tags: ["SaaS", "AI Tools"],
    pricing: "Paid",
    desc: "Enterprise-grade generative AI platform for content creation.",
    url: "#",
    color: "text-orange-400",
    bg: "bg-orange-500/10",
    icon: <Sparkles size={20} />,
    status: "Beta",
  },
  {
    name: "InstaShred",
    mainCategory: "Web Development Projects",
    tags: ["Web", "Portfolio"],
    pricing: "Free",
    desc: "Fitness and shredding platform.",
    url: "https://instashred.com/",
    previewUrl: "https://instashred.com/",
    color: "text-red-400",
    bg: "bg-red-500/10",
    icon: <Zap size={20} />,
    status: "Production",
  },
  {
    name: "Recallers",
    mainCategory: "Web Development Projects",
    tags: ["Web", "Portfolio"],
    pricing: "Free",
    desc: "Dog training and recallers platform.",
    url: "https://dogsthat.com/recallers/",
    previewUrl: "https://dogsthat.com/recallers/",
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    icon: <Globe size={20} />,
    status: "Production",
  },
];

export const reviews: ReviewType[] = [
  {
    name: "Sarah Jenkins",
    role: "CEO",
    company: "TechFlow Labs",
    location: "London, UK",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    projectCategory: "AI Automation",
    metric: "20+ hrs/wk saved",
    text: "Abdulrahman completely transformed our lead generation pipeline. The custom n8n autonomous workflow he built seamlessly synchronizes CRM records and saves our team over 20 hours every single week.",
    rating: 5,
    featured: true,
  },
  {
    name: "Rajiv Patel",
    role: "Founder & CTO",
    company: "SaaSify Cloud",
    location: "Bangalore, India",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    projectCategory: "SaaS Development",
    metric: "MVP delivered in 14 days",
    text: "Incredible AI integration skills and full-stack execution. He built our multi-tenant SaaS MVP in record time. The code structure, clean architecture, and modular UI exceeded all our expectations.",
    rating: 5,
    featured: true,
  },
  {
    name: "Michael Chen",
    role: "Director of Growth",
    company: "GrowthOps Global",
    location: "San Francisco, USA",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    projectCategory: "Web Development",
    metric: "+340% conversion rate",
    text: "The custom enterprise portal and CRM integration is flawless. Abdulrahman brings rare synergy between deep technical acumen, Apple-level UI design, and commercial conversion strategy.",
    rating: 5,
    featured: true,
  },
  {
    name: "Aisha Khan",
    role: "Head of Marketing",
    company: "MSN Global IT Solutions",
    location: "Dubai, UAE",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    projectCategory: "Design & Web Architecture",
    metric: "4.8m avg. session time",
    text: "Not just a developer, but a true product strategist. The MSN Trainings Portal and campaign video reel he crafted completely elevated our enterprise brand credibility across international markets.",
    rating: 5,
    featured: true,
  },
  {
    name: "David Wright",
    role: "VP of Product",
    company: "Vesper Systems",
    location: "Manchester, UK",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80",
    projectCategory: "AI Tools",
    metric: "4.9/5 user rating",
    text: "Vesper AI Notes is a game-changer. His ability to craft lightning-fast web workstations with tactile sound feedback, 60fps animations, and minimalist aesthetic is unmatched.",
    rating: 5,
    featured: false,
  },
  {
    name: "Priya Sharma",
    role: "E-Commerce Founder",
    company: "Junno Express",
    location: "Mumbai, India",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80",
    projectCategory: "AI Voice & Support",
    metric: "+40% CSAT score",
    text: "Automated our entire multi-channel customer support with intelligent Voice AI. We have observed a 40% rise in customer satisfaction and immediate resolution times.",
    rating: 5,
    featured: false,
  },
  {
    name: "James Wilson",
    role: "Managing Partner",
    company: "Adriel Partners",
    location: "New York, USA",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80",
    projectCategory: "UI/UX & Branding",
    metric: "$1.2M pipeline generated",
    text: "Abdulrahman's UI/UX design craft brought our luxury venture vision to life. The interactive 3D portal looks world-class and establishes immediate authority with high-ticket clients.",
    rating: 5,
    featured: false,
  },
  {
    name: "Elena Rodriguez",
    role: "Head of Operations",
    company: "Plotnao Real Estate",
    location: "Austin, USA",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80",
    projectCategory: "AI Automation",
    metric: "99.8% workflow accuracy",
    text: "We contracted him for a mission-critical multi-agent workflow and he delivered far beyond expectations. Thorough documentation, zero downtime, and stellar reliability.",
    rating: 5,
    featured: false,
  },
  {
    name: "Omar Farooq",
    role: "Tech Entrepreneur",
    company: "NeuralCraft Studio",
    location: "Edinburgh, UK",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
    projectCategory: "Open Source AI",
    metric: "10k+ active users",
    text: "His open-source repositories and AI speech engines are phenomenal. SpeakEasy AI and NodeRaptor are exceptionally engineered tools with great developer ergonomics.",
    rating: 5,
    featured: false,
  },
  {
    name: "Anita Desai",
    role: "Agency Director",
    company: "Outlab Digital",
    location: "Singapore",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400&auto=format&fit=crop&q=80",
    projectCategory: "Web Engineering",
    metric: "100% on-time delivery",
    text: "Partnering with INFNI-T was the highest-leverage decision for our agency. His frontend speed, shader effects, and strategic system architecture are unmatched.",
    rating: 5,
    featured: false,
  },
];

export const companies = [
  { name: "Plotnao", role: "Partner" },
  { name: "Adriel Partners", role: "Collaborator" },
  { name: "Content with Teeth", role: "AI Strategist" },
  { name: "Outlab", role: "Expert" },
  { name: "MSN Global IT Sol", role: "Consultant" },
];

export const skills = [
  { name: "AI Automation", icon: <Bot size={16} />, level: "Expert" },
  { name: "SaaS Development", icon: <Code size={16} />, level: "Expert" },
  { name: "Video Editing", icon: <Video size={16} />, level: "Advanced" },
  { name: "UI/UX Design", icon: <Palette size={16} />, level: "Advanced" },
  { name: "Digital Marketing", icon: <Zap size={16} />, level: "Advanced" },
  { name: "Business Strategy", icon: <Briefcase size={16} />, level: "Expert" },
];
